---
  - name: working with comparison operators
    hosts: localhost
    gather_facts: false
    vars:
      x: 10
      y: 20
    tasks:
      - debug:
          msg:
            - "x == y: {{x==y}}"
            - "x < y: {{x<y}}"
            - "x + y: {{x+y}}"
